import type { APKAnalysis } from "@/types/apk";
import { mapToOWASPTop10 } from "@/lib/owasp-mapper";

/**
 * Generates an executive Markdown report tailored for HackerOne / Bugcrowd submissions.
 */
export function generateMarkdownReport(analysis: APKAnalysis): string {
  const date = new Date(analysis.analyzedAt).toUTCString();
  const owasp = mapToOWASPTop10(analysis);
  const criticalFindings = analysis.findings.filter(f => f.severity === "critical");
  const highFindings = analysis.findings.filter(f => f.severity === "high");
  const mediumFindings = analysis.findings.filter(f => f.severity === "medium");

  return `# Security Assessment Report: ${analysis.fileName}

**Target Application:** \`${analysis.packageName || analysis.fileName}\`  
**Version:** ${analysis.versionName || "Unknown"} (Build ${analysis.versionCode || "N/A"})  
**Min / Target SDK:** API ${analysis.minSdk || "N/A"} / API ${analysis.targetSdk || "N/A"}  
**SHA-256 Digest:** \`${analysis.sha256}\`  
**Assessment Date:** ${date}  
**Auditor Engine:** APKLens Client-Side Static Analysis Suite  

---

## Executive Summary

| Metric | Value |
| :--- | :--- |
| **Total Findings** | ${analysis.findings.length} |
| **Critical Severity** | ${criticalFindings.length} |
| **High Severity** | ${highFindings.length} |
| **Medium Severity** | ${mediumFindings.length} |
| **Compiled Classes** | ${analysis.dexFiles.reduce((acc, d) => acc + (d.classCount || 0), 0).toLocaleString()} |
| **Declared Permissions** | ${analysis.permissions.length} |
| **Deep Links / URI Schemes** | ${(analysis.deepLinks || []).length} |

---

## Detailed Vulnerability Breakdown

${analysis.findings.map((f, i) => `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}

- **Severity:** \`${f.severity.toUpperCase()}\`
- **Evidence / Location:**
\`\`\`
${f.evidence}
\`\`\`
`).join("\n")}

---

## Deep Link Attack Surface (URI Schemes)

${(analysis.deepLinks || []).length > 0 ? `
| Scheme | Host | Path | Target Activity | Browsable |
| :--- | :--- | :--- | :--- | :--- |
${(analysis.deepLinks || []).map(dl => `| \`${dl.scheme}\` | \`${dl.host || "*"}\` | \`${dl.path || "/"}\` | \`${dl.activity.split(".").pop()}\` | ${dl.isBrowsable ? "✅ Yes" : "❌ No"} |`).join("\n")}

### ADB Reproduction Command:
\`\`\`bash
${(analysis.deepLinks || [])[0]?.adbCommand || "adb shell am start -W -a android.intent.action.VIEW -d \"scheme://host\""}
\`\`\`
` : "No custom URI schemes or deep links declared in AndroidManifest.xml."}

---

## OWASP Mobile Top 10 (2024) Compliance Matrix

| Category | Title | Status | Findings |
| :--- | :--- | :--- | :--- |
${owasp.map(o => `| **${o.id}** | ${o.name} | ${o.status === "pass" ? "🟢 PASS" : o.status === "warn" ? "🟡 WARN" : "🔴 FAIL"} | ${o.findings.join("; ") || "None"} |`).join("\n")}

---

*Report automatically generated by APKLens — Privacy-First Android Binary Inspection.*
`;
}

/**
 * Generates an RFC4180 compliant CSV string of all findings.
 */
export function generateCSVFindings(analysis: APKAnalysis): string {
  const headers = ["Severity", "Title", "Evidence", "Package", "File"];
  const rows = analysis.findings.map(f => [
    f.severity.toUpperCase(),
    `"${(f.title || "").replace(/"/g, '""')}"`,
    `"${(f.evidence || "").replace(/"/g, '""')}"`,
    `"${(analysis.packageName || "").replace(/"/g, '""')}"`,
    `"${(analysis.fileName || "").replace(/"/g, '""')}"`
  ]);

  return [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
}
